const pool = require('../services/db');

const SQLSTATEMENT = `
    DROP TABLE IF EXISTS "User";
    DROP TABLE IF EXISTS "WeightTracker";
    DROP TABLE IF EXISTS "Programme";
    DROP TABLE IF EXISTS "Day";
    DROP TABLE IF EXISTS "Exercise";
    DROP TABLE IF EXISTS "WorkoutLog";

    CREATE TABLE "User" (
        "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "username" TEXT NOT NULL,
        "email" TEXT NOT NULL,
        "password" TEXT NOT NULL,
        "active_programme_id" INT
    );

    CREATE TABLE "WeightTracker" (
        "weighttracker_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "user_id" INT NOT NULL,
        "weight" INT NOT NULL,
        "created_on" TIMESTAMP NOT NULL
    );

    CREATE TABLE "Programme" (
        "programme_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "user_id" INT NOT NULL
    );

    CREATE TABLE "Day" (
        "day_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "programme_id" INT NOT NULL,
        "exercise_id" INT NOT NULL,
        "day" INT NOT NULL,
        "workout_order" INT NOT NULL,
        "sets" INT NOT NULL,
        "reps" TEXT NOT NULL,
        "target_weight" INT NOT NULL
    );

    CREATE TABLE "Exercise" (
        "exercise_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "name" TEXT NOT NULL
    );

    CREATE TABLE "WorkoutLog" (
        "workoutlog_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "user_id" INT NOT NULL,
        "exercise_id" INT NOT NULL,
        "weight" TEXT NOT NULL,
        "reps" TEXT NOT NULL,
        "created_on" TIMESTAMP NOT NULL
    );
`;

pool.query(SQLSTATEMENT, (error, results, fields) => {
    if (error) {
        console.error("Error creating tables:", error);
    } else {
        console.log("Tables created successfully");
    }
    process.exit();
});
